name: All Builds (Windows, Android)

on:
  push:
    branches:
      - master
      - main

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.11.8
  FLUTTER_VERSION: 3.22.2

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      PYTHONUTF8: 1  # إضافة متغير بيئة لتفعيل UTF-8
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Flet Build Windows
      run: |
        flutter config --no-analytics
        flet build windows --verbose --no-rich-output --build-number=$env:BUILD_NUMBER --build-version=$env:BUILD_VERSION

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: windows-build-artifact
        path: build/windows
        if-no-files-found: warn
        overwrite: false

  build-apk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Flet Build APK with Background Fix
      run: |
        flutter config --no-analytics
        # بناء التطبيق مؤقتًا لإنشاء ملفات Flutter
        flet build apk --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION --no-apk
        # تعديل ملف main.dart لضمان أن الخلفية بيضاء
        sed -i "s|backgroundColor: Colors.white,|backgroundColor: Colors.white, // Ensure white background\n      scaffoldBackgroundColor: Colors.white,|" build/flutter/lib/main.dart
        # إعادة بناء APK بعد التعديل
        cd build/flutter
        flutter build apk --release --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION
        cd ../..
        # نقل ملف APK إلى المجلد المناسب
        mv build/flutter/build/app/outputs/flutter-apk/app-release.apk build/apk/app-release.apk

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: apk-build-artifact
        path: build/apk
        if-no-files-found: warn
        overwrite: false
